/*
import io.swagger.client.model.ErrorList;
import io.swagger.client.model.Error;
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.productpricing;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Schema for an individual featured offer expected price response.
 */
@ApiModel(description = "Schema for an individual featured offer expected price response.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-05-31T10:41:51.838+03:00")
public class FeaturedOfferExpectedPriceResponse {
  @SerializedName("headers")
  private HttpHeaders headers = null;

  @SerializedName("status")
  private HttpStatusLine status = null;

  @SerializedName("request")
  private FeaturedOfferExpectedPriceRequestParams request = null;

  @SerializedName("body")
  private FeaturedOfferExpectedPriceResponseBody body = null;

  public FeaturedOfferExpectedPriceResponse headers(HttpHeaders headers) {
    this.headers = headers;
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(required = true, value = "")
  public HttpHeaders getHeaders() {
    return headers;
  }

  public void setHeaders(HttpHeaders headers) {
    this.headers = headers;
  }

  public FeaturedOfferExpectedPriceResponse status(HttpStatusLine status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  public HttpStatusLine getStatus() {
    return status;
  }

  public void setStatus(HttpStatusLine status) {
    this.status = status;
  }

  public FeaturedOfferExpectedPriceResponse request(FeaturedOfferExpectedPriceRequestParams request) {
    this.request = request;
    return this;
  }

   /**
   * Use these request parameters to map the response back to the request.
   * @return request
  **/
  @ApiModelProperty(required = true, value = "Use these request parameters to map the response back to the request.")
  public FeaturedOfferExpectedPriceRequestParams getRequest() {
    return request;
  }

  public void setRequest(FeaturedOfferExpectedPriceRequestParams request) {
    this.request = request;
  }

  public FeaturedOfferExpectedPriceResponse body(FeaturedOfferExpectedPriceResponseBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public FeaturedOfferExpectedPriceResponseBody getBody() {
    return body;
  }

  public void setBody(FeaturedOfferExpectedPriceResponseBody body) {
    this.body = body;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeaturedOfferExpectedPriceResponse featuredOfferExpectedPriceResponse = (FeaturedOfferExpectedPriceResponse) o;
    return Objects.equals(this.headers, featuredOfferExpectedPriceResponse.headers) &&
        Objects.equals(this.status, featuredOfferExpectedPriceResponse.status) &&
        Objects.equals(this.request, featuredOfferExpectedPriceResponse.request) &&
        Objects.equals(this.body, featuredOfferExpectedPriceResponse.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, status, request, body);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeaturedOfferExpectedPriceResponse {\n");
    
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

