/*
import io.swagger.client.model.ErrorList;
import io.swagger.client.model.Error;
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.productpricing;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * An individual featured offer expected price request for a particular SKU.
 */
@ApiModel(description = "An individual featured offer expected price request for a particular SKU.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-05-31T10:41:51.838+03:00")
public class FeaturedOfferExpectedPriceRequest {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("method")
  private HttpMethod method = null;

  @SerializedName("body")
  private HttpBody body = null;

  @SerializedName("headers")
  private HttpHeaders headers = null;

  @SerializedName("marketplaceId")
  private String marketplaceId = null;

  @SerializedName("sku")
  private String sku = null;

  public FeaturedOfferExpectedPriceRequest uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * The URI associated with an individual request within a batch. For &#x60;FeaturedOfferExpectedPrice&#x60;, this should be &#x60;/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice&#x60;.
   * @return uri
  **/
  @ApiModelProperty(required = true, value = "The URI associated with an individual request within a batch. For `FeaturedOfferExpectedPrice`, this should be `/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice`.")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public FeaturedOfferExpectedPriceRequest method(HttpMethod method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(required = true, value = "")
  public HttpMethod getMethod() {
    return method;
  }

  public void setMethod(HttpMethod method) {
    this.method = method;
  }

  public FeaturedOfferExpectedPriceRequest body(HttpBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public HttpBody getBody() {
    return body;
  }

  public void setBody(HttpBody body) {
    this.body = body;
  }

  public FeaturedOfferExpectedPriceRequest headers(HttpHeaders headers) {
    this.headers = headers;
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(value = "")
  public HttpHeaders getHeaders() {
    return headers;
  }

  public void setHeaders(HttpHeaders headers) {
    this.headers = headers;
  }

  public FeaturedOfferExpectedPriceRequest marketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * Get marketplaceId
   * @return marketplaceId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }

  public FeaturedOfferExpectedPriceRequest sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeaturedOfferExpectedPriceRequest featuredOfferExpectedPriceRequest = (FeaturedOfferExpectedPriceRequest) o;
    return Objects.equals(this.uri, featuredOfferExpectedPriceRequest.uri) &&
        Objects.equals(this.method, featuredOfferExpectedPriceRequest.method) &&
        Objects.equals(this.body, featuredOfferExpectedPriceRequest.body) &&
        Objects.equals(this.headers, featuredOfferExpectedPriceRequest.headers) &&
        Objects.equals(this.marketplaceId, featuredOfferExpectedPriceRequest.marketplaceId) &&
        Objects.equals(this.sku, featuredOfferExpectedPriceRequest.sku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, method, body, headers, marketplaceId, sku);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeaturedOfferExpectedPriceRequest {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

